Homework5Try3/Models/students.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Homework5Try3.Models
{
    public class students
    {
        public int studentId { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public DateTime birthdate { get; set; }
        public string gender { get; set; }
        public string classs { get; set; }
        public int point { get; set; }
    }
}

Homework5Try3/Controllers/BorrowedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Homework5Try3.Models;
using Service = Homework5Try3.Models.Service;

namespace Homework5Try3.Controllers
{
    public class BorrowedController : Controller
    {
        private Service dataService = new Service();
        // GET: Borrowed
        [HttpGet]
        public ActionResult Index(int id)
        {
            var borrows = dataService.getAllBorrows(id).ToList();
            return View(borrows);
        }


    }
}

Homework5Try3/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Homework5Try3.Models;
using Service = Homework5Try3.Models.Service;

namespace Homework5Try3.Controllers
{
    public class StudentController : Controller
    {
        private Service dataService = new Service();
        // GET: Student
        [HttpGet]
        public ActionResult Index()
        {
            var student = dataService.getAllStudents().Distinct().ToList();
            return View(student);
        }

        [HttpPost]
        public ActionResult Index(string searchtext, string classs)
        { 
            List<students> students = dataService.getAllStudents().Where(x => x.name.Contains(searchtext)).ToList();
            if(classs.Length != 0)
            {
                students = students.Where(x => x.classs.Contains(classs)).ToList();
            }
            return View(students);
        }
    }
}

Homework5Try3/Views/Student/Index.cshtml
@model IEnumerable<Homework5Try3.Models.students>

@{
    ViewBag.Title = "Index";
}

<h2>Students</h2>
@using (Html.BeginForm("Index", "Student", FormMethod.Post))
{
    <div class="form-group">
        <div class="row">
            <div class="col-sm-4">
                <input class="form-control mr-sm-2" id="searchtext" name="searchtext" type="search" placeholder="Search Book Name" aria-label="Search">
            </div>

            <div class="col-sm-4">
                <select name="classs" id="classs" class="form-control" style="width: 200px;">
                    <option value="">Select Class</option>
                    @foreach (var item in Model)
                    {
                        <option value="@item.classs">@item.classs</option>
                    }
                </select>
            </div>
            <div class="col-sm-2">
                <input type="submit" class="btn btn-success" value="Search" style="width: 150px;" />
            </div>
            <div class="col-sm-2">
                <input type="submit" id="clear" class="btn btn-danger" value="Clear" style="width: 150px;" />
            </div>
        </div>
        <br />
    </div>
}
<table class="table">
    <tr>
        <th>
            #
        </th>
        <th>
            Name
        </th>
        <th>
            Surname
        </th>
        <th>
            Class
        </th>
        <th>
            Points
        </th>
        <th>
            Borrow Book
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.studentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.classs)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.point)
            </td>
            <td>
                @Html.ActionLink("Borrow Book", "Index", "Borrowed", new { }, new { @class = "btn btn-primary" })
            </td>
        </tr>
    }

</table>